# ---- Artifact Project Settings ----

# Paths containing artifact markdown/toml files
artifact_paths = ["design"]

# Paths to exclude when loading artifacts
exclude_artifact_paths = []

# Paths containing code that has artifact links
code_paths = ["src", "review_app/src"]

# Paths to exclude when searching through code
exclude_code_paths = ["review_app/src/__pycache__/"]
